import nodemailer from "nodemailer";

function buildHtmlBody(analysis: string): string {
  const escapedAnalysis = analysis
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\n/g, "<br>");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: "Courier New", Courier, monospace;
      font-size: 14px;
      line-height: 1.6;
      color: #333;
      max-width: 700px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f9f9f9;
    }
    .container {
      background: white;
      padding: 24px;
      border-radius: 8px;
      border: 1px solid #e0e0e0;
    }
    .header {
      font-size: 18px;
      font-weight: bold;
      margin-bottom: 16px;
      color: #1a1a1a;
    }
    .footer {
      margin-top: 24px;
      font-size: 12px;
      color: #888;
      border-top: 1px solid #e0e0e0;
      padding-top: 12px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">Daily Market Brief</div>
    <div>${escapedAnalysis}</div>
    <div class="footer">
      Generated by Market Tracker &mdash; AI-powered daily analysis
    </div>
  </div>
</body>
</html>`;
}

export async function sendEmail(analysis: string): Promise<void> {
  const emailFrom = process.env.EMAIL_FROM;
  const emailTo = process.env.EMAIL_TO;
  const emailPassword = process.env.EMAIL_PASSWORD;

  if (!emailFrom || !emailTo || !emailPassword) {
    throw new Error(
      "Email configuration missing. Set EMAIL_FROM, EMAIL_TO, and EMAIL_PASSWORD."
    );
  }

  const transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 465,
    secure: true,
    auth: {
      user: emailFrom,
      pass: emailPassword,
    },
  });

  const today = new Date().toISOString().split("T")[0];

  try {
    await transporter.sendMail({
      from: emailFrom,
      to: emailTo,
      subject: `📈 Daily Market Brief — ${today}`,
      text: analysis,
      html: buildHtmlBody(analysis),
    });
    console.log(`Email sent successfully to ${emailTo}`);
  } catch (error) {
    throw new Error(
      `Failed to send email: ${error instanceof Error ? error.message : error}`
    );
  }
}
